micronaut:
  application:
    name: alertservice
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
rabbitmq.uri: amqp://localhost:5672
jpa.default.properties.hibernate.hbm2ddl.auto: update
netty:
  default:
    allocator:
      max-order: 3

telegram.api.endpoint: https://api.telegram.org/bot5414437625:AAGIdMkPvKghHcHOazMgOkhLeMCCE3YUWvo

